---
# make sure homebrew is installed, update brew and install applications 

- name: application installs
  include: homebrew.yml

- name: getting downloads 
  get_url:
    url: "{{item.value.url}}"
    dest: "{{item.value.dest}}"
  with_dict: "{{downloads}}"    

- name: start installing homebrew applications
  homebrew:
    name: "{{item}}"
    state: latest
  with_items: "{{applications}}"

- name: start installing homebrew cask applications
  homebrew_cask:
    name: "{{item}}"
    state: installed 
  with_items: "{{cask_applications}}"
