---
# doing configuration

- name: setting up zsh with oh-my-zsh
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{general.local_home}}/.oh-my-zsh"

- name: getting dracula theme for oh-my-zsh
  git:
    repo: https://github.com/dracula/zsh.git
    dest: "{{general.local_home}}/.oh-my-zsh_dracula_theme"

- name: sym linking oh-my-zsh theme
  file:
    src: "{{general.local_home}}/.oh-my-zsh_dracula_theme/dracula.zsh-theme"
    dest: "{{general.local_home}}/.oh-my-zsh/themes/dracula.zsh-theme"
    state: link

- name: setting up emacs with spacemacs 
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: "{{general.local_home}}/.emacs.d"

- name: create workspace directories
  file:
    path: "{{general.local_home}}/workspace"
    state: directory

- name: create GOPATH directory
  file:
    path: "{{general.local_home}}/workspace/go"
    state: directory

- name: setting up vim-plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "{{general.local_home}}/.local/share/nvim/site/autoload/plug.vim"
  




