---
# install and update homebrew and cask

- name: install homebrew
  shell: 'yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"' 
  args:
    creates: /usr/local/bin/brew

- name: ensure homebrew is updated 
  homebrew:
    state: latest
    update_homebrew: yes

- name: tap homebrew caskroom/cask
  homebrew_tap:
    tap: "caskroom/cask"

- name: tap homebrew neovim/homebrew-neovim 
  homebrew_tap:
    tap: "neovim/homebrew-neovim"
    state: present

